project:
  type: website
  output-dir: docs

website:
  title: "Elizabeth McDaniel"
  navbar:
    right:
      - href: index.qmd
        text: About
      - href: work.qmd
        text: Work
      - href: writing.qmd
        text: Writing
      - href: contact.qmd
        text: Contact
      - href: resume.qmd
        text: Resume

format:
  html:
    theme: cosmo dark
    css: styles.css
    toc: true

editor: visual

resources:
  - CNAME
