project:
  type: website
  output-dir: docs

website:
  title: "Elizabeth McDaniel"
  navbar:
    right:
      - href: index.qmd
        text: About
      - href: publications.qmd
        text: Pubs
      - href: posts.qmd
        text: Posts
      - href: contact.qmd
        text: Contact
      - href: resume.qmd
        text: Resume

format:
  html:
    theme: cosmo dark
    css: styles.css
    toc: true

editor: visual

