---
title: "Contact Information"
editor: visual
---

Elizabeth McDaniel, PhD\
[elizabethmcd93\@gmail.com](mailto:%20elizabethmcd93@gmail.com)\

The best way to contact me is at the email address above. Arcadia Science is [reimagining scientific publishing](https://research.arcadiascience.com/reimagining-scientific-publishing) and does not publish our work in traditional peer-reviewed journals. **Therefore, I do not accept requests to review for peer-reviewed journals.** However, Arcadia Science regularly engages in reviewing preprints and posting public comments. You can view the public comments I've made on preprints through [Hypothesis](https://hypothes.is/users/elizabeth.mcdaniel). If you have a preprint that you think I might be interested in reviewing, please email me with the preprint link and I will do my best to review it and post a public comment. My expertise spans environmental microbiology and computational biology, with specific emphasis on microbial ecology of engineered water systems and multi-omics approaches.

During my PhD and postdoc, I was incredibly dedicated to practicing reproducible and open research by publicly providing associated code and datasets with each of my publications. For each manuscript on my [Publications](https://elizabethmcd.github.io/publications/) page, I have provided a PDF copy for download, links to code workflows available on Github, datasets on Figshare, and/or genomes/meta-omics datasets available on NCBI. Should you have any problems downloading a manuscript that may be behind a paywall for you, or have any questions about my code/datasets, please do not hesitate to contact me at the email address above.
