---
title: "What I've Learned Transitioning from Academia to Industry (So Far)"
date: "2025-03-16"
description: "Advice from transitioning from academia to industry roles, based on what I've learned"
categories: [advice, industry]
author: Elizabeth McDaniel
---

From time-to-time life scientists entering the industry job market after finishing their PhD/postdoc will ask me for advice on how to best position themselves for making this transition. In general, I think advice is super subjective and people oftentimes leave out how much luck or circumstances [^1] at the time played a part in how they ended up where they are now. However, there are some general things I've learned since making this transition almost three years ago [^2] and have since found myself repeatedly telling others these little tips. Therefore, I'm motivated to write these learnings out in the hopes they are helpful to others on the job market and a more high-throughput way of reaching people than 1:1 conversation.

[^1]: My personal circumstances when I was a postdoc looking for industry jobs: I started my PhD in Microbiology in fall of 2016 and finished in summer of 2021. I did a short \~10 month postdoc and started looking for industry jobs in spring of 2022. My background is microbial metagenomics/multi-'omics, and I have some amount of wet-lab experience. Since fall of 2022 I've worked in industry settings in the San Francisco Bay Area, albeit not those super typical of traditional biotech. If I remember correctly, I applied to 5 jobs in industry – 2 never responded, 1 responded 5 months later (after I had a job offer), I had 1 informational interview before the company had a hiring freeze, and I had 1 full set of interviews that led to a job offer. All the jobs I applied to were computational biology/bioinformatics scientist roles with a metagenomics/microbial focus and I was looking to be on-site full-time with whatever job offer I ended up with, as it was just me and my cat and I wasn't specifically constrained on geographic location.

[^2]: I have no idea if any of these learnings actually help with finding a job, especially in the current job market environment. Since I've only worked in two non-traditional companies that are sort of like early-stage startups, I also don't know if these learnings are useful to applying to larger companies or in the government sector. I've seen some of these things recommended by other people, but YMMV.

### **In academia, the signal is novelty. In industry, the signal is *utility.***

This is by far the most important lesson I've learned. All the advice I give usually stems in some way directly from this statement, so I think it's important to expand on this.

Now, before you get all up in arms that I'm insinuating that academia doesn't do useful science or biotech doesn't do novel science, that's not what I'm saying. What I am saying is that these sectors operate differently because the end goals and outputs are vastly different. At least historically this has been the case; time will tell if this trend shifts. Therefore, the primary signal that you project when interviewing for jobs and even when hired in the role is important.

For example, (currently) the business of academia outside of teaching/mentoring/service is to do science that can get you published in peer-reviewed journals so you can get grants and then do more science, publish more papers, and get more grants and keep the cycle going. By and large the way you successfully get published and grant funding is by underscoring the *novelty* of your work. (Think "This has never been observed before, we are to our knowledge the first to show this, this is a new technology etc.")

In industry, while companies are working to bring to market products that might not exist already or bring some notable improvement to existing products, the novelty of the science is not necessarily the most important aspect of running a company. At the end of the day, the most crucial goal of a company is to find the right product-market fit for their technology to eventually be profitable. Or put another way, the product has enough demonstrated *utility* that people will buy it.

This point was made super clear to me when I recently took a short version of the [NSF Innovation Corps (I-Corps)](https://www.nsf.gov/funding/initiatives/i-corps) course, where their mission is to help scientists translate technologies from the lab to the marketplace, primarily by conducting customer discovery interviews. The biggest take-home I took away from that course is that customers, which may be the general consumer, doctors, health insurance providers, other scientists etc., don't actually care about the inner workings of your technology. They care that your technology solves a real problem they have and at a price point they can afford.

So, how do you make sure you are sending across a signal of utility when applying for jobs in industry?

### **Get straight to the point and highlight what is directly relevant**

Try to put yourself in the shoes of the hiring manager for the role. They are likely receiving 10s-100s of applications for a single role, and therefore are probably spending less than a couple minutes looking through your application, if that.

The multi-page CV where you've listed every publication, conference presentation, award, and committee you've participated in is the exact opposite of what you want to send to potential employers. A concise, 1 page resume highlighting relevant skills, work/research experience, and \*select\* publications is ideal. Make sure to put your skills towards the top of your resume; when hiring managers are scanning through endless resumes they are looking to see if your skillset aligns with the responsibilities of the role.

For comparison, [here](https://github.com/elizabethmcd/cv/blob/master/EAM-CV.pdf) is what my academic CV used to look like (I stopped updating it years ago, and I just update my personal website from time to time), and [here](https://elizabethmcd.github.io/resume.html) is what my most up-to-date resume looks like. The jobs I've applied to didn't require or have an option to submit a cover letter or statement, so I opted for a short bio section at the top of my resume that I slightly tailored for each job application.

### **Make yourself visible beyond journal publications**

Relying solely on journal publications to convey who you are as a scientist and the work you've done is not wise. For one, if your work isn't published in an open-access journal, it's very likely the hiring manager isn't going to be able to even read your work because a lot of companies don't pay for journal subscriptions. It's fantastic for your job prospects (and science!) if you have posted preprints of your work. This is especially helpful if you have publications undergoing peer-review – it's really difficult to show your utility by just listing "Article Title (Under Review)" on your CV and nothing else to show for it.

However, related to the above point that hiring managers don't spend a lot of time on each application, how do you increase your visibility beyond long-form research articles?

The simplest and most obvious outlet is LinkedIn. This platform is used very little in most academic circles, but the least you should do is have an up-to-date profile. This includes a profile picture, your education and work/research history. Make sure to highlight your skills here as well and not just summarize your dissertation research and publications. This is also a great place to see what companies or roles alumni from your graduate program have ended up in and contact them to see if they would be willing to talk about their experience.

Another way to increase your visibility is to have a personal website. It's a different outlet to highlight your background and skills, and you can add a blog if you want to. I don't think having a blog is absolutely necessary, but sometimes a personal website with the addition of a blog can help with reaching people outside of your network. For example, if you write a tutorial about a computational tool, or a short post about an emerging area of science, this demonstrates your communication skills outside of the formality of a journal publication. I personally use [Quarto](https://quarto.org/) for building my personal website and blog posts, but there's a lot of different tools to build a personal website or blog.

If you're trying to land a computational or bioinformatics role, or just want to specifically highlight your coding skills, have an active GitHub profile. This is pretty crucial especially if you are applying for computational roles, as it can be difficult to assess the level of a candidate's skill just from journal articles alone (and again, a hiring manager isn't spending their time combing through the methods of your publications to figure this out), and putting your code on GitHub is a pretty low lift way to showcase your skills. In addition to just putting your code on GitHub, you can differentiate yourself by adding sufficient documentation to your repositories, specifically highlighting how somebody else can use your code or tool.

### **Seek out networking hangouts and informational interviews**

There's several groups that host in-person networking events or have associated Slack groups that are valuable places to meet people or find out about job listings. The ones I know of and participate in are [BitsinBio](https://www.bitsinbio.org/), [TechBio Transformers](https://linktr.ee/techbiotransformers), and Climate Hangouts and Climate Biotech Community hosted by [Homeworld Collective](https://www.homeworld.bio/). These are also just fun places to meet people working on similar things even if you already have a job. These types of hangouts can be more relevant and helpful than going to traditional conferences to meet people, unless you know that there will be a fair amount of people from industry attending the conference you'll be at.

Importantly, I think the most appropriate way to reach out to individuals on LinkedIn, TwitterX, or Bluesky etc. that you don't personally know or don't have a mutual connection to is to politely ask if they would be willing to talk about their experience. Jumping straight to asking them to refer you for a role in their company in my opinion doesn't seem like a great approach for a myriad of reasons – the largest reason being they don't know you, and the technical reason being they might not even be involved or aware of the role you are applying to. Sometimes reaching out to somebody at a company that's hiring is referred to as an "informational interview" if you want to specifically talk about that company or role. Reaching out to people in industry with a similar background to yours just to learn about their path is fine, again just ask politely.

### **Use AI tools, but wisely**

This was not a lesson I learned while transitioning from academia to industry, but AI tools are already very prevalent in the way people are finding and applying for jobs and subsequently performing their work. A couple caveats to these opinions. The first is that this is a fast-moving area, and I'll probably have updated opinions on using AI tools in the not-so-distant future, but here's what I think for now. The second is that the below is influenced by my time in startup spaces, and I don't yet know exactly how larger biotech companies are embracing AI tools at the moment.

My optimistic take of AI is that you should use this as a tool to learn new things and be more efficient. Maybe you want to learn about machine learning algorithms and how to apply them to biological data. You could create a personalized learning plan around a project tailored to your interests with the help of a chatbot. Or maybe you could make your workflow more efficient by using a tool like Cursor to write better code.

My skeptical take of AI tools right now is that these tools still struggle with bioinformatics tasks, as demonstrated by the [benchmark FutureHouse put out recently](https://www.futurehouse.org/research-announcements/bixbench) evaluating AI agents on different bioinformatics tasks. I expect that this will improve over time with better models and more tailored products and training for bioinformatics-specific tasks. But for now you should still exercise caution and implement tests for your code.

My incredibly strong and somewhat pessimistic take on AI tools is that you shouldn't use them to completely replace your original thinking. Essentially, I don't think you should use AI tools to 100% write cover letters, short answer questions, code problems etc. to help apply for a higher volume of jobs. Even if companies are embracing AI tools for you to be more efficient in your work, you still need to assess if the output is correct for your use case and make informed decisions. It's incredibly hard to assess if you have the necessary skills to do that if your job application is 100% AI generated.

I totally get that people feel motivated to use AI tools for applying to jobs because the market is incredibly tough right now and there's a sense AI will help with the ability to apply to a higher volume of jobs and therefore increase changes of an interview etc. However, I still strongly feel that being intentional with the jobs you apply to and tailoring your materials for the given role is important. Then again, I might be totally wrong and update this opinion in the future. Time will tell.
