---
title: "What I Learned Getting my PhD in Microbiology"
date: "2025-05-19"
description: "Advice for getting a PhD in the life sciences"
categories: [advice, grad school]
author: Elizabeth McDaniel
---

There are basically only two topics that I feel I can give generally actionable “advice” on. One is [how to make the transition from academia to industry](../2025-03-16-academia-to-industry/index.qmd). The other is going to grad school and getting a PhD in the life sciences. I feel inclined to write about my thoughts on getting a PhD in the life sciences for the same reason that I wrote my transitioning to industry post – 1) There are some things that I’ve found myself repeating a lot over the years, and writing them down might help reach more people, and 2) This is another area where people don’t acknowledge enough how luck is a huge factor in where they ended up, and I think that’s super important context to remember when making your own decisions.

I particularly remember a time where a friend asked advice about going to grad school and said they thought the way I approached my scientific training was the right way. To which I immediately laughed and made it very clear that I didn’t intentionally plan the vast majority of what happened [^1]. Most of my decisions were fueled by what I was most interested in at the time, and I chose environments that I thought could best foster those interests. And those environments led to new things to be curious and learn about, which led to new people, which led to new environments and so and so forth.

[^1]: Similar to my industry post, I’ve written out a brief summary of my personal circumstances and path through science as a footnote. Although I think most advice posts would have the below stories woven into the advice parts, I think it’s mostly distracting from the main points. But I still want to demonstrate how just being curious or lucky at pivotal points really have more to do with where I am now than some grand plan. <p> I entered college in 2012 wanting to be a medical doctor, because I didn’t know what else you could do if you loved science. This desire started to fade in the middle of my freshman year when 1) I realized I probably couldn’t deal with human bodily fluids and functions, 2) I started to meet scientific researchers that got a PhD, and 3) I started my own research experience. The honors program I was in required at least 2 years of research, but since in the middle of freshman year I wasn’t totally sold on wanting to be a medical doctor, I started scrolling through the list of professors in the biology department that might have research openings for undergrads. I remember around that time I was fascinated in general about pathogen evolution and maybe wanted to research that. The lab I ended up joining did work on microbial evolution, but not specifically on pathogens. But it was the best environment and set of mentors I could have asked for where I was able to be curious, learn how to design experiments, keep trying after an experiment went wrong, and develop my writing skills. I originally was a Spanish minor (because I thought it would pair well with going to medical school) but wasn’t enjoying it. I switched to minoring in Statistics, and in my senior year took some programming classes both through my stats coursework and a programming for biology course. This is where the pieces started to come together that I really enjoyed computational biology and wanted to do more analytical work paired with microbial evolution. <p> I applied to 6 graduate programs – two different programs at University of Washington, two different programs at University of Wisconsin – Madison, a large umbrella program at University of North Carolina, and Emory University. The unifying theme of where I applied was that I wanted a large-ish program that I could rotate through labs, because I really didn’t know what I wanted to do. And I had basically also been given the advice that rotating through labs is a good idea to make sure you are a good fit with the lab, mentor, etc. I knew broadly I was interested in microbial evolution and further developing my computational skills, but beyond that I didn’t know any specifics, not even what types of careers I would want after graduate school. I ended up going on three interviews and entered the Microbiology Doctoral Training Program at UW-Madison in fall of 2016. <p> MDTP required a minimum of three rotations, and I ended up doing four because at the end of my three rotations I hadn’t found the right fit. At the time, the perfectionist, high-achieving parts of me saw this as a colossal failure, because I was the only one in my cohort that hadn’t joined a lab. But I talked to other students in my program that had previously done multiple rotations, and the common sentiment was they were actually happier with their choice because they had really taken the time to make sure they found the right fit rather than just forcing a decision to fit in. And this was exactly the case for me. The lab I ended up joining was probably the furthest from my radar, and I had actually crossed it off the list because I didn’t do “ecology or engineering” which were elements of what the lab did. But they were working on really interesting microbial evolution problems using computational tools, and I really felt I could fit well with the PI and the lab culture. Now I love thinking about applied biotechnology and microbiology problems. And the rest is history.

The below advice doesn’t really cover *applying* to graduate school. It’s been \~10 years since I did that myself, and so much has changed about that process since I went through it, I don’t think I could give useful advice [^2].

[^2]: Context for when I applied to grad school in 2015 – the GRE was still required, being an author on a publication wasn’t an “unwritten requirement,” and I didn’t have my own independent funding that I had been awarded. I had \~2 full years of research experience at the time of applying, primarily at my undergrad institution but also one summer internship experience. Nowadays a lot has changed that I don’t even know what to recommend to prospective grad students other than to have research experience of some sort so they have an idea of if they even enjoy that sort of work. Everything else involving the GRE (or not), grades, research experience, publications, funding, recommendation letters, etc. I’ve been too far removed from to be helpful.

### Do what you love, not what you think you should love.

Getting a PhD is a marathon, not a sprint. And if you choose a certain path just to check off a list of marketable skills or techniques that you don’t really care about, you are probably going to be very miserable halfway through when you have a mountain of failed experiments and ideas that didn’t pan out. This is always my response to questions of “should I specialize in X field or skill,” (lately that’s been flavors of bioinformatics, AI, and/or protein design) or something else that is really big and hot right now. If you are really interested in that field or technique, great! If you are just doing it because it’s the thing to chase at the moment, that’s probably a great recipe for unhappiness.

Now, this is different from advice about what *tools* or general skills you might want to learn in your area of interest. Maybe you don’t want to specialize in bioinformatics or computational biology, but generally having some basic analytical skills is a good idea for reproducible research and adding it to your resume. Same with whatever is the newest ‘omics technology – maybe it’s going to be useful for your research question, maybe not. In general, I think there are going to be plenty of opportunities for you to learn marketable skills in a research area you are genuinely interested in.

### Look for clear signs of values that align with yours and what you want in the future.

The best piece of advice I was given about grad school is that it’s what *you* make of it. Getting a PhD differs in a lot of ways from going through professional programs like medical or dental school etc. Those programs have a very prescribed set of courses, standardized tests, and checkboxes to tick off before you can move on to being a practicing doctor. Other than a qualifying exam and dissertation defense (which even those can differ vastly program to program), you get to make what you get out of grad school in a very flexible way. If you know you want to end up in industry afterwards, find programs that encourage or explicitly require through fellowships industry internships. If you know you want to improve your computational skills, take specific courses or short workshops. If you know you want to go specifically into teaching, find programs where you can have a lot of classroom experience. And so and so forth.

Now, I think the common counterargument that people will have that they can’t accomplish specifically want they want to do because the name of the game in academia is just focusing on research to publish as fast and as frequently as possible. And that therefore mentors and programs aren’t going to be supportive or encouraging of these other activities like industry internships, teaching, science communications efforts etc. This is certainly true of certain mentors and programs! There’s this common quip thrown around academia that a lot of the bad behaviors or inefficiency of the system are due to the incentives placed upon researchers to play and stay in the game. That is, the need to publish in journals (oftentimes high impact, “glam” journals), to then get grants, to then do the science, and feed the cycle etc. But I don’t necessarily think that’s true.

I remember in grad school overhearing a professor say it was on their professional bucket list to publish in *Natur*e. And I distinctly remember my gut instinct was one of confusion and I didn’t relate at all. But you personally might really identify with striving to publish in *Cell, Nature*, and or *Science*. I personally wanted to work towards making useful tools and resources, which meant gravitating towards labs and people that posted preprints, put their code on GitHub, and made data openly available. These things don’t have to be mutually exclusive, but that’s sometimes how it plays out. Now, the question if what people value and strive for is actually best for science and sharing knowledge is for a different blog post. I can say that if you eventually want a job outside of academia, posting preprints and code on GitHub is very much in your best interest. Hiring managers aren’t going to automatically assume skills that you have certain skills but they can’t verify because your main dissertation work is in the process of a months to years long review at a journal. And truly, posting openly is better for science anyways.

### Increase your chances to find the unexpected.

Grad school is maybe one of the few or only times in your professional life where you have dedicated time to completely immerse yourself in what you are curious about. Granted you might have some teaching responsibilities and need to apply for grants etc., but by and large this is the largest amount of uninterrupted time to really learn and be as open and curious as possible about new things. You could make the argument that postdocs and professors are doing this as well, but I think to a lesser degree. The point of a postdoc is to really specialize and find a job, whether that be as a professor or in industry. Professors are juggling many responsibilities to an even greater degree – teaching, grant writing, administrative duties, etc. that there is even less time for uninterrupted and curiosity-fueled thinking and learning. So, take advantage of this time while you can. 

The very opposite of taking advantage of this unique gift of time is entering grad school and acting like you have already learned what there is to learn about your given topic, and you just have to crank things out at a breakneck speed. Not playing the productivity competition game with others was probably the hardest lesson for me to learn. The “I worked 12+ hours every day for the last month” or “I’m so busy with X number of collaborations, getting ready for Y conference talks” game that you play at happy hours that somehow factor into the number of hours worked that day. Not only is this a recipe for burnout, but you are essentially sacrificing this precious gift for something that might resemble it but is greatly cheapened.

I do generally recommend, even if you do know what general area of study you want to go in, to go through a program that has rotations. I had really no idea what topic I wanted to spend the next \~5 years of my life deeply studying, other than I loved microbial evolution and wanted to advance my computational skills. So going through rotations was incredibly beneficial for me and led me to joining a lab I never would have joined through direct admit. Rotating through labs can also help you decide on the non-science aspects of a lab – are you and the mentor a good fit for each other, do you like the lab dynamics, do you *actually want* to spend the next \~5 years doing what that lab does?

Hopefully there are some useful and actionable tips here. But overall, try to engineer your path for ways that increase your chances of luck that aligns with what you love to do, and spend less time trying to follow a prescribed plan.
