---
title: "For the love of physical books"
date: "2026-06-01"
description: "Why I still buy physical books in the age of e-readers"
categories: [books]
author: Elizabeth McDaniel
---

Every time I move apartments or find myself twiddling my thumbs on delayed transit, I ask myself the same question. *Why do I have so many physical books and not yet indulged in the convenience and space-saving wonders of an e-reader?* It’s a question my mother also asks me constantly with a horrified look at my bookshelves as she tries to add up how much I’ve spent on hardbacks (always a waste to not wait for the paperback version, in her opinion).

But over time, I’ve found a lot of reasons to love reading and keep buying physical books, some of them surprisingly pro-social, which have kept me from buying an e-reader.

### *Swapping books with friends*

This is my top reason to keep buying physical books. I am very loose with loaning out my books, especially if they are one of my favorites (except for a signed *Stephen King* novel). If a friend mentions a book that I own they want to read or I notice it shelved on their Goodreads, I’ll happily loan it to them. Over time I’ve noticed this brings me a lot of joy to be able to loan out books to friends. I’ve never been able to quite pinpoint why this brings me so much joy, other than I’ve always loved giving gifts and that I’ll eventually have somebody else to talk about a favorite book with. I’ve also enjoyed the reverse, especially when a friend noticed I had a book on my Goodreads and saw it at an estate sale and gave it to me[^1].

[^1]: Everyone should have a Goodreads, IMO.

### *The happy dance when I receive a pre-ordered book in the mail*

The past couple of years I’ve had the practice of asking for Barnes and Noble gift cards for Christmas, and then I pre-order upcoming new book releases for the following year that I’m excited about. I even add an event in my calendar for when I’m expecting a new book to be shipped so I can plan my reading list accordingly around it. Even though it’s not exactly a surprise when it arrives, I always do a little happy dance when the package arrives on my doorstop. I’ve also experienced the same joy when I pick up books from the library that I’ve placed on hold. I don’t have a particular reason for this joy, other than delayed gratification at work.

### *Chatting with a stranger about the book I’m/they are currently reading*

Reading a book on transit or at a restaurant usually translates to other people as “don’t talk to me.” I’ve personally never felt that way when doing so, and it’s also led to some of my most memorable conversations and book recommendations. A couple of years ago I was reading *Unsheltered* by Barbara Kingsolver at a crowded bar in a restaurant by myself. There was a group next to me getting ready to leave when I heard an excited gasp and one of the women asked if I was enjoying my book. After I said I was and briefly summarized the plot thus far, she said I had to read *Demon Copperhead* by Kingsolver, as it made her rethink how to be a better person in the world. What a way to describe the effect of a book on a person!

A different time, I noticed the person next to me was reading *The Martian* by Andy Weir. Since *Project Hail Mary* was released in 2021, I’ve used any remotely relevant reason to bring the book up in conversation and urge others to read it. With the movie coming out in just a few months, I had to chat with the person next to me if she was enjoyed *The Martian* and if she had read *Project Hail Mary*, to which she excitedly replied was next on her to-read list.

### *Giving new life to books I didn’t finish or don’t want to keep on my shelves*

Starting in 2024, I finally started DNFing (did not finish) books that I wasn’t thoroughly enjoying or at least intrigued by where it was going. Previously I would slog through a book or put it down and say I would come back to it when I was in the mood, with no regard to if I would enjoy finishing the book. I don’t know why I engaged in this torture, other than up to that point I had a deep belief I had to finish the things I started. Since freeing myself of this belief, the quickest I’ve DNFed a book was page 15, with my usual quit time around page 100 if it’s a 400/500 page book. I’ll then wait until I have a stack of books I DNFed or don’t want to keep on my shelf and take them to neighborhood library boxes, or previously Half Priced Books (RIP the Berkeley HPB location). Even though I didn’t enjoy the book, it gives me a small amount of joy that eventually the book will find its’ way to someone that will enjoy it.

Compare this to an e-book I decided to not finish, I almost felt distressed at not being able to rid myself of it. Yes, I can delete it from my downloaded books as to relieve my tablet from the weight of something I detested so much. But it doesn’t quite bring the same satisfaction as releasing a physical book out into the world to find someone that will love it properly.

### *The calming feeling I experience in a bookstore or library*

Whenever I’m feely particularly down, I will find myself in a bookstore or library. For a while I attributed this to my need to buy and consume things when upset, as this was a similar behavior to clothes shopping to fill an emotional void. But once I tampered down on emotional purchases, I still found myself drawn to bookstores and libraries when feeling blue but didn’t feel the urge to have to buy or check out something. Just purusing the shelves and updating my “To Read” shelf on Goodreads is enough to lift my spirits, knowing that I can buy or loan the book later when I want to. This feeling can’t be replicated scrolling through the Kindle store.

### *The reprieve at the end of the day from screens*

This is probably the top reason I’ve avoided purchasing an e-reader. Even though Kindles don’t have other apps to be distracted by like on a conventional tablet, I still find myself rejecting the idea of looking at another screen at the end of the day. Something about holding a physical book at the end of a long day in bed, trying to stay awake long enough to just finish the current chapter.

### *The case for e-readers*

Over time, I’ve only found three convincing reasons to buy an e-reader. The first two reasons are the obvious reasons of saving space in my apartment and thus the number of boxes when I inevitably must move them to a new apartment, and the convenience of being able to read whenever I want when out and about (provided I remember to pack said e-reader).

The third reason, which has only come up recently and almost made buying an e-reader a priority, is reducing the pain in my wrists from holding large books for long periods of time. Holding an e-reader presents the same problem, but there are a lot of solutions such as the e-reader sleeves and book pillows that are popular on Tiktok/Instagram. I never experienced this problem until I read the paperback version of *The Overstory*, and I don’t have a good solution for reducing the strain on my wrists, especially for paperback books that can’t be set on a pillow or lap table as easily as hardcover books.
